package com.ujjwalbhardwaj.intuit.profile.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ujjwalbhardwaj.intuit.profile.entity.model.Address;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@DynamoDBTable(tableName = "Profile")
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Profile {
    @DynamoDBHashKey
    private String id;

    @DynamoDBAttribute
    private String companyName;

    @DynamoDBAttribute
    private String legalName;

    @DynamoDBAttribute
    private Address businessAddress;

    @DynamoDBAttribute
    private Address legalAddress;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String website;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;
}

