package com.ujjwalbhardwaj.intuit.profile.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ujjwalbhardwaj.intuit.commons.enums.EventType;
import com.ujjwalbhardwaj.intuit.commons.enums.Product;
import com.ujjwalbhardwaj.intuit.profile.entity.convertor.ProductListConvertor;
import com.ujjwalbhardwaj.intuit.profile.entity.convertor.StringListConvertor;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;
import java.util.Set;

@DynamoDBTable(tableName = "ProfileValidationRequest")
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ProfileValidationRequest {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String businessId;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = ProductListConvertor.class)
    private Set<Product> subscribedProducts;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = ProductListConvertor.class)
    private Set<Product> approvals;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = ProductListConvertor.class)
    private Set<Product> rejections;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBTypeConverted(converter = StringListConvertor.class)
    private List<String> rejectionReasons;

    @DynamoDBTypeConvertedEnum
    private EventType eventType;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;
}
